# algerian fire forest dataset

this dataset includes 244 instances that regroup a data of two regions of algeria namely bajaia region located in northeast of algeria and sidi-bel-abbes region located in northwest of algeria.
122 instances for each region.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv('Algerian_forest_fires_dataset_UPDATE.csv' , header=1)

In [3]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    str
 1   month        245 non-null    str
 2   year         245 non-null    str
 3   Temperature  245 non-null    str
 4    RH          245 non-null    str
 5    Ws          245 non-null    str
 6   Rain         245 non-null    str
 7   FFMC         245 non-null    str
 8   DMC          245 non-null    str
 9   DC           245 non-null    str
 10  ISI          245 non-null    str
 11  BUI          245 non-null    str
 12  FWI          245 non-null    str
 13  Classes      244 non-null    str
dtypes: str(14)
memory usage: 27.0 KB

In [5]:
df[df.isnull().any(axis=1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,14,07,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

the dataset is converted into two sets based on region fromm 122th index , we can make new column based on region 
1. Bejaia region dataset
2. sidi-bel-abbes region

In [6]:
df.loc[:122,'region']=0
df.loc[122:,'region']=1

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    str
 1   month        245 non-null    str
 2   year         245 non-null    str
 3   Temperature  245 non-null    str
 4    RH          245 non-null    str
 5    Ws          245 non-null    str
 6   Rain         245 non-null    str
 7   FFMC         245 non-null    str
 8   DMC          245 non-null    str
 9   DC           245 non-null    str
 10  ISI          245 non-null    str
 11  BUI          245 non-null    str
 12  FWI          245 non-null    str
 13  Classes      244 non-null    str
 14  region       246 non-null    float64
dtypes: float64(1), str(14)
memory usage: 29.0 KB

In [7]:
### converting float values to int

df[['region']]= df[['region']].astype(int)

In [8]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,region
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,0
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,0
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,0

In [9]:
df.tail()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,region
241,26,09,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire,1
242,27,09,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire,1
243,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire,1
244,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire,1
245,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire,1

In [10]:
df.isnull().sum()

day            0
month          1
year           1
Temperature    1
 RH            1
 Ws            1
Rain           1
FFMC           1
DMC            1
DC             1
ISI            1
BUI            1
FWI            1
Classes        2
region         0
dtype: int64

In [11]:
## removing 122 rows from dataset
df=df.dropna().reset_index(drop=True)
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,region
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,0
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,0
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,0

In [12]:
df.isnull().sum()

day            0
month          0
year           0
Temperature    0
 RH            0
 Ws            0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
region         0
dtype: int64

In [13]:
df.iloc[[122]]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,region
122,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,1

In [14]:
## droping 122 row

df=df.drop(122).reset_index(drop=True)

In [15]:
df.iloc[[122]]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,region
122,01,06,2012,32,71,12,0.7,57.1,2.5,8.2,0.6,2.8,0.2,not fire,1

In [16]:
df.columns

Index(['day', 'month', 'year', 'Temperature', ' RH', ' Ws', 'Rain ', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes  ', 'region'],
      dtype='str')

In [17]:
## removing extra space in column names
df.columns=df.columns.str.strip()
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'region'],
      dtype='str')

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    str
 1   month        243 non-null    str
 2   year         243 non-null    str
 3   Temperature  243 non-null    str
 4   RH           243 non-null    str
 5   Ws           243 non-null    str
 6   Rain         243 non-null    str
 7   FFMC         243 non-null    str
 8   DMC          243 non-null    str
 9   DC           243 non-null    str
 10  ISI          243 non-null    str
 11  BUI          243 non-null    str
 12  FWI          243 non-null    str
 13  Classes      243 non-null    str
 14  region       243 non-null    int64
dtypes: int64(1), str(14)
memory usage: 28.6 KB

In [19]:
## changes the required columns as int datatypes
df[['day', 'month', 'year', 'Temperature', 'RH']] = df[['day', 'month', 'year', 'Temperature', 'RH']].astype(int)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    str
 6   Rain         243 non-null    str
 7   FFMC         243 non-null    str
 8   DMC          243 non-null    str
 9   DC           243 non-null    str
 10  ISI          243 non-null    str
 11  BUI          243 non-null    str
 12  FWI          243 non-null    str
 13  Classes      243 non-null    str
 14  region       243 non-null    int64
dtypes: int64(6), str(9)
memory usage: 28.6 KB

In [21]:
## changing to float data types
objects=[features for features in df.columns if df[features].dtype == 'str']

In [22]:
for i in objects:
    if i!= 'Classes':
        df[i]=df[i].astype(float)

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    float64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    str
 14  region       243 non-null    int64
dtypes: float64(8), int64(6), str(1)
memory usage: 28.6 KB

In [25]:
## lets save cleaned dataset
df.to_csv('Algerian_forest_fires_cleaned_dataset.csv' , index=False)

In [31]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,region
0,1,6,2012,29,57,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,2,6,2012,29,61,13.0,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire,0
2,3,6,2012,26,82,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,4,6,2012,25,89,13.0,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire,0
4,5,6,2012,27,77,16.0,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire,0

In [42]:
df['Classes'].value_counts()

Classes
fire             131
not fire         101
fire               4
fire               2
not fire           2
not fire           1
not fire           1
not fire           1
Name: count, dtype: int64

In [45]:
df_copy= df

In [46]:
## exploratory data analysis
## droping day month and year 
df_copy=df.drop(['day','month','year'] , axis=1)

In [29]:
df_copy.head()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,region
0,29,57,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,29,61,13.0,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire,0
2,26,82,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,25,89,13.0,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire,0
4,27,77,16.0,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire,0

In [47]:
## Encoding of categories in classes

df_copy['Classes']=np.where(df_copy['Classes'].str.contains('not fire'),0,1)

In [48]:
df_copy.head()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,region
0,29,57,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0,0
1,29,61,13.0,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0,0
2,26,82,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0,0
3,25,89,13.0,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0,0
4,27,77,16.0,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0,0

In [49]:
df_copy.tail()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,region
238,30,65,14.0,0.0,85.4,16.0,44.5,4.5,16.9,6.5,1,1
239,28,87,15.0,4.4,41.1,6.5,8.0,0.1,6.2,0.0,0,1
240,27,87,29.0,0.5,45.9,3.5,7.9,0.4,3.4,0.2,0,1
241,24,54,18.0,0.1,79.7,4.3,15.2,1.7,5.1,0.7,0,1
242,24,64,15.0,0.2,67.3,3.8,16.5,1.2,4.8,0.5,0,1

In [50]:
df_copy['Classes'].value_counts()

Classes
1    137
0    106
Name: count, dtype: int64